### PR TITLE
JUnit Reintroduction and Class Creation

### PR DESCRIPTION
**Pull request by dominias**
Reintroduced JUnit and created classes for divorce report, review, and workflow with a basic review JavaFX screen set up.

### CODE REVIEW

**Review by NathanielDYoung — APPROVED** [review]
Looks good

**Review by NathanielDYoung — APPROVED** [review]
Approving class name changes here

**Comment by smoola913** [comment]
Everything seems to be working

**Review by smoola913 — COMMENTED** [review]
Closed before I had a chance to review but additions and changes seem to be working

**Pull request merged**
